apiVersion: v1
kind: Namespace
metadata:
  name: ns1
---
apiVersion: v1
kind: Namespace
metadata:
  name: ns2
---
apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: test-vpc-1
spec:
  namespaces:
    - ns1
---
apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: test-vpc-2
spec:
  namespaces:
    - ns2
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: subnet1
spec:
  vpc: test-vpc-1
  cidrBlock: 10.0.1.0/24
  protocol: IPv4
  natOutgoing: true
  namespaces: 
    - ns1
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: subnet2
spec:
  vpc: test-vpc-2
  cidrBlock: 10.0.1.0/24
  protocol: IPv4
  natOutgoing: true
  namespaces:
    - ns2
---
apiVersion: v1
kind: Pod
metadata:
  namespace: ns1
  name: pod-1-1
  annotations:
    ovn.kubernetes.io/logical_switch: "subnet1"
spec:
  containers:
    - name: test-1-1
      image: nicolaka/netshoot:v0.13
      command: ["sleep", "infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  namespace: ns1
  name: pod-1-2
  annotations:
    ovn.kubernetes.io/logical_switch: "subnet1"
spec:
  containers:
    - name: test-1-2
      image: nicolaka/netshoot:v0.13
      command: ["sleep", "infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  namespace: ns2
  name: pod-2-1
  annotations:
    ovn.kubernetes.io/logical_switch: "subnet2"
spec:
  containers:
    - name: test-2-1
      image: nicolaka/netshoot:v0.13
      command: ["sleep", "infinity"]
---
apiVersion: v1
kind: Pod
metadata:
  namespace: ns2
  name: pod-2-2
  annotations:
    ovn.kubernetes.io/logical_switch: "subnet2"
spec:
  containers:
    - name: test-2-2
      image: nicolaka/netshoot:v0.13
      command: ["sleep", "infinity"]

