apiVersion: v1
kind: Namespace
metadata:
  name: ns1
---
apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: test-vpc-1
spec:
  policyRoutes:
    - action: reroute
      match: ip4.src == 10.0.1.0/24
      nextHopIP: 10.0.1.254
      priority: 10
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: test-external-network
  namespace: ns1
spec:
  protocol: IPv4
  provider: test-external-network.kube-system
  cidrBlock: 10.233.0.0/16
  gateway: 10.233.233.233  # IP address of the physical gateway
  excludeIps:
  - 10.233.0.1..10.233.234.0
---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: test-external-network
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "master": "ens192",
      "mode": "bridge",
      "ipam": {
        "type": "kube-ovn",
        "server_socket": "/run/openvswitch/kube-ovn-daemon.sock",
        "provider": "test-external-network.kube-system"
      }
    }'
---
apiVersion: kubeovn.io/v1
kind: Subnet
metadata:
  name: net1
  namespace: ns1
spec:
  vpc: test-vpc-1
  cidrBlock: 10.0.1.0/24
  protocol: IPv4
---
apiVersion: kubeovn.io/v1
kind: VpcNatGateway
metadata:
  name: gw1
  namespace: ns1
spec:
  vpc: test-vpc-1
  subnet: net1
  lanIp: 10.0.1.254
  externalSubnets:
    - test-external-network
---
apiVersion: kubeovn.io/v1
kind: IptablesEIP
metadata:
  name: eip01
  namespace: ns1
spec:
  natGwDp: gw1
  externalSubnet: test-external-network
---
apiVersion: kubeovn.io/v1
kind: IptablesSnatRule
metadata:
  name: snat01
  namespace: ns1
spec:
  eip: eip01
  internalCIDR: 10.0.1.0/24
---
apiVersion: v1
kind: Pod
metadata:
  namespace: ns1
  name: pod-1-1
  annotations:
    ovn.kubernetes.io/logical_switch: "net1"
    ovn.kubernetes.io/ip_address: "10.0.1.10"
spec:
  containers:
    - name: test-1-1
      image: docker.0rays.club/cbctf/netshoot:v0.13
      command: ["sleep", "infinity"]

