apiVersion: v1
kind: Namespace
metadata:
  name: ns1
---
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: net1
spec:
  cidrBlock: 10.0.1.0/24
  protocol: IPv4
  namespaces:
    - ns1
---
apiVersion: v1
kind: Pod
metadata:
  namespace: ns1
  name: test-pod
  annotations:
    ovn.kubernetes.io/logical_switch: "net1"
    ovn.kubernetes.io/ip_address: "10.0.1.10"
spec:
  containers:
    - name: test
      image: nicolaka/netshoot:v0.13
      command: ["sleep", "infinity"]
