apiVersion: v1
kind: Namespace
metadata:
  name: ns1
---
apiVersion: kubeovn.io/v1
kind: Vpc
metadata:
  name: test-vpc-1
---
kind: Subnet
apiVersion: kubeovn.io/v1
metadata:
  name: net1
spec:
  vpc: test-vpc-1
  cidrBlock: 10.0.1.0/24
  protocol: IPv4
---
apiVersion: kubeovn.io/v1
kind: IP
metadata:
  name: test-pod.ns1
spec:
  subnet: net1
  podType: ""
  namespace: ns1
  podName: test-pod
  v4IpAddress: 10.0.1.10
---
apiVersion: v1
kind: Pod
metadata:
  namespace: ns1
  name: test-pod
  labels:
    app: test
  annotations:
    ovn.kubernetes.io/logical_switch: "net1"
    ovn.kubernetes.io/ip_address: "10.0.1.10"
spec:
  containers:
    - name: test
      image: nicolaka/netshoot:v0.13
      command: ["sleep", "infinity"]
